version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: robot-dashboard
    container_name: robot-dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # Persistent data storage
    devices:
      - /dev/video0:/dev/video0  # USB Camera
    group_add:
      - video
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 800M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
